// Generated by CoffeeScript 1.7.1
var check, ctn, dgi, dgi1, dgn, dgt;

dgi = function(t) {
  return document.getElementById(t);
};

dgi1 = function(t) {
  return document.getElementById(t);
};

dgt = function(t) {
  return document.getElementsByTagName(t);
};

dgn = function(t) {
  return document.getElementsByName(t);
};

ctn = function(t) {
  return document.createTextNode(t);
};

check = function() {
  var e, el, errp, form, howmanys, namelen, res, txt;
  e = dgi('name');
  errp = dgi('inputErrors');
  howmanys = dgn("howmany");
  res = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = howmanys.length; _i < _len; _i++) {
      el = howmanys[_i];
      if (el.checked === true) {
        _results.push(el);
      }
    }
    return _results;
  })();
  namelen = e.value.trim().length;
  form = dgt("form")[0];
  errp.textContent = "";
  switch ([res.length === 0, namelen === 0].join()) {
    case "true,true":
      txt = ctn(" No name given and no friends selected!");
      return errp.appendChild(txt);
    case "true,false":
      txt = ctn(" No friends selected!");
      return errp.appendChild(txt);
    case "false,true":
      txt = ctn(" No name given!");
      return errp.appendChild(txt);
    case "false,false":
      return form.submit();
  }
};
